# **Numpy**  

# Methods in Numpy
.ravel() flattens dataset
.reshape() reshapes dataset
.resize()
.arange()

In [2]:
import numpy as np


In [4]:
np_sqrt = np.sqrt([9,37,38,18])

In [5]:
first_numpy_array = np.array([373,37,13,232,87])

In [6]:
print(first_numpy_array)

[373  37  13 232  87]


In [8]:
array_with_zeros = np.zeros((2,3,4,5))
array_with_zeros

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [9]:
array_with_empty = np.empty((3,4))
array_with_empty

array([[1.2416573e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [12]:
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np_linspace = np.linspace(3,6,9)
print(np_linspace)

[3.    3.375 3.75  4.125 4.5   4.875 5.25  5.625 6.   ]


In [19]:
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [22]:
twoD_array = oneD_array.reshape(3,5)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [25]:
import numpy as np

In [26]:
np.array(24)

array(24)

In [27]:
np.array([1,2,3,45,6,7]) #1D Array

array([ 1,  2,  3, 45,  6,  7])

In [29]:
np.array([[1,2,3,4],[5,6,7,8]]) #2D Array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #3D Array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [33]:
numpy_arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #3D Array

In [36]:
numpy_arr.shape #Shape of the array

(2, 2, 4)

In [37]:
numpy_arr.ndim #Dimension

3

In [38]:
numpy_arr = np.array([x for x in range(1,10)])
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
numpy_arr = np.array([x for x in range(1,13)])
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [43]:
numpy_arr.reshape(2,2,-1) #Use for Dynamic Dataset

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
numpy_arr = numpy_arr.reshape(3,2,2)
print(numpy_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [48]:
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Arithmetic Operation in Python

In [52]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([3,5,7])

In [53]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
B

array([3, 5, 7])

In [55]:
np.add(A,B)

array([[ 4,  7, 10],
       [ 7, 10, 13]])

In [56]:
np.subtract(B,A)

array([[ 2,  3,  4],
       [-1,  0,  1]])

In [57]:
np.multiply(A,B)

array([[ 3, 10, 21],
       [12, 25, 42]])

In [58]:
np.divide(A,B)

array([[0.33333333, 0.4       , 0.42857143],
       [1.33333333, 1.        , 0.85714286]])

In [59]:
np.power(A,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

# Conditional Statement in Python

In [69]:
x = np.array([i for i in range(10)])

In [70]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [72]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [73]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

# Common Mathematical and Statistical Functions in NUMPy

In [76]:
arr1 = np.array([[1,2,3],[4,7,9],[3,1,8]])

In [77]:
arr1

array([[1, 2, 3],
       [4, 7, 9],
       [3, 1, 8]])

In [79]:
np.amin(arr1)

1

In [80]:
np.amin(arr1,axis=0) #Vertical Column of the array, axis = 0

array([1, 1, 3])

In [82]:
np.amin(arr1,axis=0) #Horizontal Column of the array, axis = 0

array([1, 4, 1])

In [83]:
np.amax(arr1)

9

In [88]:
np.amax(arr1,axis=0) #Vertical Column of the array, axis = 0

array([4, 7, 9])

In [89]:
np.amax(arr1,axis=1) #Horizontal  Column of the array, axis = 1

array([3, 9, 8])

In [90]:
np.median(arr1)

3.0

In [92]:
np.mean(arr1)

4.222222222222222

In [93]:
np.std(arr1)

2.8588178511708016

In [94]:
np.var(arr1)

8.17283950617284

In [95]:
np.percentile(arr1,50)

3.0

In [96]:
deg = np.array([0,30,45,60,90])

In [98]:
np.sin(deg+np.pi/180) #Degrees into radians

array([ 0.01745241, -0.98518908,  0.85994206, -0.3213861 ,  0.88604054])

In [99]:
np.cos(deg+np.pi/180) #Degrees into radians

array([ 0.9998477 ,  0.17147149,  0.51039167, -0.94694824, -0.46360777])

In [100]:
np.tan(deg+np.pi/180) #Degrees into radians

array([ 0.01745506, -5.74549801,  1.68486697,  0.33939141, -1.91118572])

In [101]:
'''
arcsin
arccos
arctan
'''

'\narcsin\narccos\narctan\n'

In [102]:
arr2 = np.array([7,1,3,6,2,4,7,8.2])

In [103]:
np.floor(arr2)

array([7., 1., 3., 6., 2., 4., 7., 8.])

In [104]:
np.ceil(arr2)

array([7., 1., 3., 6., 2., 4., 7., 9.])