# **Numpy**  

# Methods in Numpy
.ravel() flattens dataset
.reshape() reshapes dataset
.resize()
.arange()

In [ ]:
import numpy as np


In [ ]:
np_sqrt = np.sqrt([9,37,38,18])

In [ ]:
first_numpy_array = np.array([373,37,13,232,87])

In [ ]:
print(first_numpy_array)

[373  37  13 232  87]


In [ ]:
array_with_zeros = np.zeros((2,3,4,5))
array_with_zeros

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [ ]:
array_with_empty = np.empty((3,4))
array_with_empty

array([[1.2416573e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np_linspace = np.linspace(3,6,9)
print(np_linspace)

[3.    3.375 3.75  4.125 4.5   4.875 5.25  5.625 6.   ]


In [ ]:
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
twoD_array = oneD_array.reshape(3,5)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
import numpy as np

In [ ]:
np.array(24)

array(24)

In [ ]:
np.array([1,2,3,45,6,7]) #1D Array

array([ 1,  2,  3, 45,  6,  7])

In [ ]:
np.array([[1,2,3,4],[5,6,7,8]]) #2D Array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #3D Array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
numpy_arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #3D Array

In [ ]:
numpy_arr.shape #Shape of the array

(2, 2, 4)

In [ ]:
numpy_arr.ndim #Dimension

3

In [ ]:
numpy_arr = np.array([x for x in range(1,10)])
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numpy_arr = np.array([x for x in range(1,13)])
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
numpy_arr.reshape(2,2,-1) #Use for Dynamic Dataset

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
numpy_arr = numpy_arr.reshape(3,2,2)
print(numpy_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Arithmetic Operation in Python

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([3,5,7])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
B

array([3, 5, 7])

In [ ]:
np.add(A,B)

array([[ 4,  7, 10],
       [ 7, 10, 13]])

In [ ]:
np.subtract(B,A)

array([[ 2,  3,  4],
       [-1,  0,  1]])

In [ ]:
np.multiply(A,B)

array([[ 3, 10, 21],
       [12, 25, 42]])

In [ ]:
np.divide(A,B)

array([[0.33333333, 0.4       , 0.42857143],
       [1.33333333, 1.        , 0.85714286]])

In [ ]:
np.power(A,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

# Conditional Statement in Python

In [ ]:
x = np.array([i for i in range(10)])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [ ]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [ ]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

# Common Mathematical and Statistical Functions in NUMPy

In [ ]:
arr1 = np.array([[1,2,3],[4,7,9],[3,1,8]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 7, 9],
       [3, 1, 8]])

In [ ]:
np.amin(arr1)

1

In [ ]:
np.amin(arr1,axis=0) #Vertical Column of the array, axis = 0

array([1, 1, 3])

In [ ]:
np.amin(arr1,axis=0) #Horizontal Column of the array, axis = 0

array([1, 4, 1])

In [ ]:
np.amax(arr1)

9

In [ ]:
np.amax(arr1,axis=0) #Vertical Column of the array, axis = 0

array([4, 7, 9])

In [ ]:
np.amax(arr1,axis=1) #Horizontal  Column of the array, axis = 1

array([3, 9, 8])

In [ ]:
np.median(arr1)

3.0

In [ ]:
np.mean(arr1)

4.222222222222222

In [ ]:
np.std(arr1)

2.8588178511708016

In [ ]:
np.var(arr1)

8.17283950617284

In [ ]:
np.percentile(arr1,50)

3.0

In [ ]:
deg = np.array([0,30,45,60,90])

In [ ]:
np.sin(deg+np.pi/180) #Degrees into radians

array([ 0.01745241, -0.98518908,  0.85994206, -0.3213861 ,  0.88604054])

In [ ]:
np.cos(deg+np.pi/180) #Degrees into radians

array([ 0.9998477 ,  0.17147149,  0.51039167, -0.94694824, -0.46360777])

In [ ]:
np.tan(deg+np.pi/180) #Degrees into radians

array([ 0.01745506, -5.74549801,  1.68486697,  0.33939141, -1.91118572])

In [ ]:
'''
arcsin
arccos
arctan
'''

'\narcsin\narccos\narctan\n'

In [ ]:
arr2 = np.array([7,1,3,6,2,4,7,8.2])

In [ ]:
np.floor(arr2)

array([7., 1., 3., 6., 2., 4., 7., 8.])

In [ ]:
np.ceil(arr2)

array([7., 1., 3., 6., 2., 4., 7., 9.])

# **Indexing and Slicing in Python Part A**

In [ ]:
import numpy as np

In [ ]:

# 1D array with 5 elements
arr_1d = np.array([1, 2, 3, 4, 5])

# 2D array with 2 rows and 3 columns
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3D array with 2 planes, 3 rows, and 4 columns
arr_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                   [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])


In [ ]:
arr_1d[0]

1

In [ ]:
arr_1d[1]

2

In [ ]:
arr_1d[-1]

5

In [ ]:
arr_2d 

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_2d[0,0]

1

In [ ]:
arr_2d[0,1]

2

In [ ]:
arr_2d[1,-1]

6

In [ ]:
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
arr_3d[0,1,2]

7

In [ ]:
arr_3d[1,1,-1]

20

# **Indexing and Slicing in Python Part B**

In [ ]:

# 1D array with 5 elements
arr_1d = np.array([1, 2, 3, 4, 5])

# 2D array with 2 rows and 3 columns
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3D array with 2 planes, 3 rows, and 4 columns
arr_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                   [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

In [ ]:
arr_1d 

array([1, 2, 3, 4, 5])

In [ ]:
arr_1d[1:]

array([2, 3, 4, 5])

In [ ]:
arr_1d[2:4]

array([3, 4])

In [ ]:
arr_1d[-3:-1]

array([3, 4])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_2d[1,1:]

array([5, 6])

In [ ]:
arr_2d[-2:-3:-1]

array([[1, 2, 3]])

In [ ]:
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [30]:
arr_3d[1,1:]

array([[17, 18, 19, 20],
       [21, 22, 23, 24]])

In [35]:
arr_2d[1,1:2]

array([5])